################################# Default configuration ###################
baseURL = "https://mystifying-curie-8264cb.netlify.app"
title = "KWYK"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

  
############################## navigation ###############################

# main menu
[[menu.main]]
name = "About"
URL = "about"
weight = 1

#[[menu.main]]
#name = "DJs"
#URL = "djs"
#weight = 2

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

# [[menu.main]]
# weight = 4
# name = "DJs"

#  [[menu.main]]
# parent = "Pages"
# name = "FAQ"
# URL = "faq"

  [[menu.main]]
#  parent = "Pages"
  weight = 2 
  name = "DJs"
  URL = "pricing"
  
[[menu.main]]
name = "Contact"
URL = "contact"
weight = 5


# footer menu
[[menu.footer]]
name = "About"
URL = "about"
weight = 1

[[menu.footer]]
name = "DJs"
URL = "djs"
weight = 2

[[menu.footer]]
name = "DJs"
URL = "pricing"
weight = 3

# [[menu.footer]]
# name = "FAQ"
# URL = "faq"
# weight = 4

[[menu.footer]]
name = "Contact"
URL = "contact"
weight = 5


#################### default parameters ################################
[params]
logo = "images/94.9-KWYK-radio.png"
# Meta data
description = ""
author = "Themefisher"
# Contact Information
phone = "505-325-1996"
email = "info@email.com"
location = "1515 W Main St, Farmington, NM 87401"
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = true
gmap_api = "https://www.google.com/maps/@36.7312048,-108.2320123,17z"
map_latitude = "36.7312048"
map_longitude = "-108.2320123,17z"
map_marker = "images/marker.png"

  
############################# social site ########################
[[params.social]]
icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"